<x-searchable-select-style />
<div class="wrapper ville-wrapper">
    <div
        class="select-btn bg-white flex min-h-[60px] flex-col-reverse justify-center rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:shadow-inner">
        <input type="text" name="ville" id="ville"
            class="peer block w-full border-0 p-0 text-base text-gray-900 placeholder-gray-400 focus:ring-0"
            placeholder="{{ $value ?? $slot }}" required/>
        <label html="ville"
            class="block transform text-xs font-bold uppercase text-gray-400 transition-opacity, duration-200 peer-placeholder-shown:h-0 peer-placeholder-shown:-translate-y-full peer-placeholder-shown:opacity-0">{{ $value ?? $slot }}</label>
    </div>
    <div class="content">
    <ul class="options cursor-pointer"></ul>
    </div>
</div>
<script>
    const wrapper = document.querySelector(".ville-wrapper"),
    selectBtn = wrapper.querySelector(".select-btn"),
    searchInp = wrapper.querySelector("input"),
    options = wrapper.querySelector(".options");

let villes = ["ACHERES",
    "ALFORTVILLE",
    "ANTONY",
    "ARGENTEUIL",
    "ARNOUVILLE LES GONESSE",
    "ARPAJON",
    "ASNIERES SUR SEINE",
    "AUBERGENVILLE",
    "AUBERVILLIERS",
    "AULNAY SOUS BOIS",
    "BAGNOLET",
    "BAILLET EN France",
    "BALLANCOURT",
    "BEAUCHAMP",
    "BEAUMONT SUR OISE",
    "BESSANCOURT",
    "BEYNES",
    "BEZONS",
    "BIEVRES",
    "BOBIGNY",
    "BOIS D'ARCY",
    "BOIS D'ARCY ",
    "BONDOUFLE",
    "BONDY",
    "BONNEUIL SUR MARNE",
    "BOULOGNE BILLANCOURT",
    "BOURG LA REINE",
    "BRETIGNY SUR ORGE",
    "BREUILLET",
    "BRIE COMTE ROBERT",
    "BRUYERE LE CHATEL",
    "BUSSY SAINT GEORGES",
    "CACHAN",
    "CARRIERES SOUS POISSY",
    "CARRIERES SUR SEINE",
    "CERGY",
    "CHAMPS SUR MARNE",
    "CHARNY",
    "CHATILLON",
    "CHATOU",
    "CHAVENAY",
    "CHAVILLE",
    "CHELLES",
    "CHELLES ",
    "CHENNEVIERES / MARNE",
    "CHESSY",
    "CHEVILLY LARUE",
    "CLAMART",
    "CLICHY",
    "CLICHY SOUS BOIS",
    "COLOMBES",
    "CONFLANS STE HONORINE",
    "CORBEIL ESSONNE",
    "CORBEIL ESSONNES",
    "CORMEILLES EN PARISIS",
    "COUBERT",
    "COUPVRAY",
    "COUPVRAY TB",
    "COURBEVOIE",
    "COURDIMANCHE",
    "CREIL",
    "CREPY EN VALOIS",
    "CRETEIL",
    "DAMMARIE LES LYS",
    "DAMMARTIN EN GOELLE",
    "DEUIL LA BARRE",
    "DOURDAN ",
    "DRANCY",
    "DRAVEIL",
    "DREUX",
    "EAUBONNE",
    "ECQUEVILLY",
    "ENNERY",
    "EPINAY SUR ORGE",
    "EPINAY SUR SORGE",
    "EPONE",
    "ERAGNY SUR OISE",
    "ERMONT",
    "ETAMPES",
    "EVREUX",
    "EVRY",
    "FLEURY MEROGIS",
    "FONTENAY SOUS BOIS",
    "FRANCONVILLE",
    "FREPILLON",
    "GAGNY",
    "GARCHES",
    "GARGENVILLE",
    "GARGES LES GONESSE",
    "GARGES LES GONESSES",
    "GENNEVILLIERS",
    "GENTILLY",
    "GIF SUR YVETTE",
    "GUIGNES",
    "HERBLAY",
    "HOUILLES",
    "IGNY",
    "ISSOU",
    "ISSY LES MOULINEAUX",
    "IVRY SUR SEINE",
    "JOINVILLE LE PONT",
    "JOUY EN JOSAS",
    "JOUY LE MOUTIER",
    "JUVISY SUR ORGE",
    "JUZIERS",
    "LA GARENNE COLOMBES",
    "LA NORVILLE",
    "LAGNY SUR MARNE",
    "LAMORLAYE",
    "LE BLANC MESNIL",
    "LE BLANC MESNIL T3",
    "LE CHESNAY",
    "LE KREMLIN BICETRE",
    "LE MEE SUR SEINE",
    "LE MESNIL LE ROI",
    "LE MESNIL SAINT DENIS",
    "LE PERREUX SUR MARNE",
    "LE PLESSIS BOUCHARD",
    "LE PLESSIS ROBINSON",
    "LE PLESSIS TREVISE",
    "LE PORT MARLY",
    "LE PRE SAINT GERVAIS",
    "LE RAINCY",
    "LES CLAYES SOUS BOIS",
    "LES LILAS",
    "L'HAY LES ROSES",
    "LIEUSAINT",
    "L'ILE SAINT DENIS",
    "L'ISLE ADAM",
    "LIVRY GARGAN",
    "LONGJUMEAU",
    "LOUVRES",
    "LUCÉ",
    "MAFFLIERS",
    "MAGNY LE HONGRE",
    "MAISONS ALFORT",
    "MAISONS LAFFITTE",
    "MALAKOFF",
    "MAREIL SUR MAULDRE",
    "MARINES",
    "MARLES EN BRIE",
    "MARLY LE ROI",
    "MAROLLES EN HURPOIX",
    "MASSY",
    "MAUREPAS",
    "MEAUX",
    "MEAUX ",
    "MELUN",
    "MENNECY",
    "MENUCOURT",
    "MERY SUR OISE",
    "MEULAN EN YVELINES",
    "MEZIERES SUR SEINE",
    "MOISSY CRAMAYEL",
    "MONTEREAU FAULT YONNE",
    "MONTESSON",
    "MONTEVRAIN",
    "MONTFERMEIL",
    "MONTFERMEIL ",
    "MONTFORT L'AMAURY",
    "MONTGERON",
    "MONTIGNY LE BRETONNEUX",
    "MONTLHERY",
    "MONTMAGNY",
    "MONTMORENCY",
    "MONTROUGE",
    "MONTROUGE ",
    "MONTROUGE Ginoux",
    "MONTROUGE Henri",
    "MORAINVILLIERS",
    "NANTERRE",
    "NEAUPHLE LE VIEUX",
    "NEUILLY SUR MARNE",
    "NOGENT  SUR  MARNE",
    "NOGENT SUR MARNE",
    "NOISEAU",
    "NOISY LE GRAND",
    "NOISY LE ROI",
    "NOISY LE SEC",
    "ORGEVAL",
    "ORLY",
    "ORMESSON SUR MARNE",
    "ORMOY",
    "ORSAY",
    "OSNY",
    "OZOIR LA FERRIERE",
    "PANTIN",
    "PARAY VIEILLE POSTE",
    "PARIS 11 rue Oberkampf",
    "PARIS 18",
    "PARIS 20",
    "PARIS 20 ème",
    "PARIS 7 ",
    "PARIS 7 Rue Oudinot",
    "PAVILLONS SOUS BOIS",
    "PERSAN",
    "PIERREFITTE",
    "PIERRELAYE",
    "PLAISIR",
    "POISSY",
    "PONTAULT COMBAULT",
    "PONTOISE",
    "PRESLES",
    "PUISEUX EN France",
    "PUTEAUX",
    "RAMBOUILLET",
    "ROCQUENCOURT",
    "ROISSY EN BRIE",
    "ROMAINVILLE",
    "ROMAINVILLE ",
    "ROSNY SOUS BOIS",
    "RUEIL MALMAISON",
    "SAINT CLOUD",
    "SAINT CYR L'ECOLE",
    "SAINT GERMAIN EN LAYE",
    "SAINT LEU LA FORET",
    "SAINT MAUR DES FOSSE",
    "SAINT MAUR DES FOSSES",
    "SAINT MAURICE",
    "SAINT MICHEL SUR ORGE",
    "SAINT OUEN",
    "SAINT OUEN L'AUMONE",
    "SAINT OUEN SUR SEINE",
    "SAINT PIERRE DU PERRAY",
    "SAINT WITZ",
    "SAINTE GENEVIEVE DES BOIS",
    "SANNOIS",
    "SANTENY",
    "SARTROUVILLE",
    "SARTROUVILLE ",
    "SAULX LES CHARTREUX",
    "SAVIGNY LE TEMPLE",
    "SAVIGNY SUR ORGE",
    "SERRIS",
    "SEVRAN",
    "SOISSONS",
    "SOISY SUR SEINE",
    "ST CYR L'ECOLE",
    "ST GERMAIN EN LAYE",
    "ST MAUR DES FOSSES",
    "Ste GENEVIEVE DES BOIS",
    "SUCY EN BRIE",
    "SURESNES",
    "TACOIGNIERES",
    "THIAIS",
    "TRAPPES",
    "TREMBLAY EN France",
    "TRIEL SUR SEINE",
    "VANVES",
    "VANVES PAIX",
    "VAUJOURS",
    "VAUREAL",
    "VELIZY VILLACOUBLAY",
    "VENEUX LES SABLONS",
    "VERNEUIL SUR SEINE",
    "VERSAILLES",
    "VIGNEUX",
    "VIGNEUX SUR SEINE",
    "VILLABE",
    "VILLEJUIF",
    "VILLEJUST",
    "VILLEMOMBLE",
    "VILLENEUVE LE COMTE",
    "VILLENEUVE LE ROI",
    "VILLENNES SUR SEINE",
    "VILLEPARISIS",
    "VILLEPINTE",
    "VILLERS SAINT FREDERIC",
    "VILLIERS SUR MARNE ",
    "VINCENNES",
    "VIROFLAY",
    "VITRY SUR SEINE",
    "VOISINS LE BRETONNEUX"];

function addVille(selectedCountry) {
    options.innerHTML = "";
    villes.forEach(country => {
        let isSelected = country == selectedCountry ? "selected" : "";
        let li = `<li onclick="updateName(this)" class="flex items-center ${isSelected}">${country}</li>`;
        options.insertAdjacentHTML("beforeend", li);
    });
}
addVille();

function updateName(selectedLi) {
    searchInp.value = "";
    addVille(selectedLi.innerText);
    wrapper.classList.remove("active");
    selectBtn.firstElementChild.value = selectedLi.innerText;
}

searchInp.addEventListener("keyup", () => {
    let arr = [];
    let searchWord = searchInp.value.toLowerCase();
    arr = villes.filter(data => {
        return data.toLowerCase().startsWith(searchWord);
    }).map(data => {
        let isSelected = data == selectBtn.firstElementChild.value ? "selected" : "";
        return `<li onclick="updateName(this)" class="flex items-center ${isSelected}">${data}</li>`;
    }).join("");
    options.innerHTML = arr ? arr : `<p style="margin-top: 10px;">Oops! Ville introuvable</p>`;
});

selectBtn.addEventListener("click", () => wrapper.classList.toggle("active"));
</script>