<x-searchable-select-style />
<div class="wrapper promoteur-wrapper">
    <div
        class="select-btn bg-white flex min-h-[60px] flex-col-reverse justify-center rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:shadow-inner">
        <input type="text" name="promoteur" id="promoteur"
            class="peer block w-full border-0 p-0 text-base text-gray-900 placeholder-gray-400 focus:ring-0"
            placeholder="{{ $value ?? $slot }}" required/>
        <label html="promoteur"
            class="block transform text-xs font-bold uppercase text-gray-400 transition-opacity, duration-200 peer-placeholder-shown:h-0 peer-placeholder-shown:-translate-y-full peer-placeholder-shown:opacity-0">{{ $value ?? $slot }}</label>
    </div>
    <div class="content">
    <ul class="options cursor-pointer"></ul>
    </div>
</div>
<script>
    const promoteurWrapper = document.querySelector(".promoteur-wrapper"),
    promoteurSelectBtn = promoteurWrapper.querySelector(".select-btn"),
    promoteurSearchInp = promoteurWrapper.querySelector("input"),
    promoteurOptions = promoteurWrapper.querySelector(".options");

let promoteurs = ["1001 VIES HABITAT",
                    "AB GROUP",
                    "ACCUEIL IMMOBILIER",
                    "ACLL",
                    "ADI PROMOTION",
                    "AEGIDE",
                    "AIGO PROMOTION",
                    "AKERYS",
                    "ALILA PROMOTION",
                    "ALIOS",
                    "ALTAREA COGEDIM",
                    "ANTIN RESIDENCE",
                    "APIC",
                    "ARC GESTION",
                    "ARCADE",
                    "ARCHIVAL",
                    "ARTENOVA",
                    "ATEC",
                    "ATIC / U2C",
                    "ATLAND",
                    "B&G PROMOTEUR",
                    "BANITI",
                    "BATEG",
                    "BATI RENOV",
                    "BATICEL",
                    "BATISSEURS FRANCILIENS",
                    "BELDEMEURE",
                    "BERGERAL",
                    "BET ANTIOPE",
                    "BET IMOE",
                    "BETIBA",
                    "BGH",
                    "BIRLOUEZ",
                    "BMG ",
                    "BNP",
                    "BNP IMMOBILIER",
                    "BNP PARIBAS",
                    "BONHOMME",
                    "BONNET",
                    "BONNEVIE & FILS",
                    "BOUYGUES BAT",
                    "BOUYGUES CONSTRUCTION",
                    "BOUYGUES DCMI",
                    "BOUYGUES IMMOBILIER",
                    "BPCC",
                    "BPD MARIGNAN",
                    "BRICQUEVILLE",
                    "BSM",
                    "BTP & PATRIMOINE",
                    "BUILD ONE",
                    "C2A ARCHITECTURES",
                    "CA IMMOBILIER",
                    "Cab ARVA",
                    "Cabinet JLB",
                    "CABINET RACINE",
                    "CAPELLI",
                    "CARE PROMOTION",
                    "CBC",
                    "CECPAD",
                    "CERP",
                    "CG PROM",
                    "CLORELICE",
                    "COBELBA",
                    "CODOPROM",
                    "COGEDIM",
                    "COLIBRI",
                    "COPIMO",
                    "COREDIF",
                    "COSTANTINI",
                    "COTTIN CONSTRUCTEURS",
                    "CREDIT AGRICOLE",
                    "CUILLER FRERES",
                    "DAVRIL",
                    "DEMATHIEU & BARD",
                    "DEMATHIEU ET BARD",
                    "DHORMES Architecte",
                    "DIAGONALE",
                    "DUMEZ",
                    "ECOLOGIA",
                    "ECOTECH",
                    "EDELIS",
                    "EIFFAGE",
                    "EIFFAGE LEFORT",
                    "ELGEA",
                    "ELGEA HABITAT",
                    "ELLEBOODE",
                    "ELYCITE",
                    "EMERIGE",
                    "EXCELYA",
                    "FAUBOURG IMMOBILIER",
                    "FIR DEVELOPPEMENT",
                    "FLORIAN D'HORMES ARCHITECTE",
                    "FONCIER CONSTRUCTION",
                    "FRANCO SUISSE",
                    "FRATERNITE SAINT JEAN",
                    "FRG / ATLAND",
                    "GAMBETTA",
                    "GCC",
                    "GENERALE DE PROMOTION",
                    "GIPEN",
                    "GLOBAL ARCHITECTURE",
                    "GRAND PARIS PROMOTION",
                    "GREEN CITY",
                    "GREENWOOD",
                    "GROUPE ARC",
                    "GROUPE ARCADE",
                    "Groupe HOCHE",
                    "GROUPE PICHET",
                    "GTM",
                    "GTPR",
                    "H&A ARCHITECTURE",
                    "HAVIM",
                    "HERACLES",
                    "HOME CONCEPT",
                    "HOME INGENIERIE",
                    "I 3 F",
                    "ICADE",
                    "ICADE PROMOTION",
                    "IMMOBEL",
                    "INTERCONSTRUCTION",
                    "INTERPROMOTION",
                    "ITB 77",
                    "JCB INGENIERIE",
                    "KAUFMAN & BROAD",
                    "KAUFMAN & BROAD   ",
                    "L&P IMMOBILIER",
                    "LEGENDRE",
                    "LEGENDRE CONST.",
                    "LEGENDRE IMMOBILIER",
                    "LES BATISSEURS FRANCILIENS",
                    "LES MACONS PARISIENS",
                    "LES NOUVEAUX CONSTRUCTEURS",
                    "LMP",
                    "LNC",
                    "LOGEMENT FRANCILIEN",
                    "LOGIPOSTEL",
                    "LTE",
                    "M & S",
                    "M & S HABITAT",
                    "MAILYS CONCEPT",
                    "MARIGNAN",
                    "MATEC ",
                    "MODAFIM",
                    "NACARAT",
                    "NAFILYAN & PARTNERS",
                    "NAFILYAN PARTNERS",
                    "NAFILYANS & PARTNERS",
                    "NAFLYIAN PARTNERS",
                    "NCN BATIMENT",
                    "NEXITY",
                    "NOVALYS",
                    "OGIC",
                    "OPTIBRIC",
                    "OSICA / CUILLIERS",
                    "OTCI",
                    "OTI",
                    "PARDEAU MORIN",
                    "PARTENAIRES ARCHITECTES",
                    "PARTICULIER PROMOGIM",
                    "PECORARI",
                    "PICHET",
                    "PIERRE ETOILE",
                    "PIERREVAL",
                    "PILASTRE",
                    "PITCH PROMOTION",
                    "PITEL",
                    "PITTEL",
                    "PREFERENCE HOME ",
                    "PRO LOGIS",
                    "PROMO GERIM",
                    "PROMOFI",
                    "PROMOGERIM",
                    "PROMOGIM",
                    "QUANIM",
                    "QUARTUS",
                    "RABOT DUTILLEUL",
                    "RCPI",
                    "REBOURG",
                    "RIVP",
                    "ROC",
                    "ROTH",
                    "SACIEG",
                    "SAINT FAUBOURG",
                    "SBG LUTECE",
                    "SCI EMERAUDE",
                    "SCM",
                    "SD INGENIERIE",
                    "SEFRI CIME",
                    "SEGER",
                    "SEMO",
                    "SEPIMO",
                    "SEQUEBAT",
                    "SICRA",
                    "SIMOBER",
                    "SNERCT",
                    "SNRB",
                    "SOFAPROM",
                    "SOFERIM",
                    "SOGEA",
                    "SOGEPROM",
                    "STEVA",
                    "STRATO",
                    "SVM PROMOTION",
                    "SYNTHESE INGENIERIE",
                    "TBI",
                    "TECSERAL",
                    "TEMPERE",
                    "TERIDEAL",
                    "TRADI ART",
                    "U2C",
                    "VAILLANTIS",
                    "VERDOIA",
                    "VERRECCHIA",
                    "VINCI CONSTRUCTION",
                    "VINCI IMMOBILIER",
                    "WINDSOR",
                    "YUME / SOFAPROM",
                    "ZUB"];

function addPromoteur(selectedCountry) {
    promoteurOptions.innerHTML = "";
    promoteurs.forEach(country => {
        let isSelected = country == selectedCountry ? "selected" : "";
        let li = `<li onclick="updatePromoteurName(this)" class="flex items-center ${isSelected}">${country}</li>`;
        promoteurOptions.insertAdjacentHTML("beforeend", li);
    });
}
addPromoteur();

function updatePromoteurName(selectedLi) {
    promoteurSearchInp.value = "";
    addPromoteur(selectedLi.innerText);
    promoteurWrapper.classList.remove("active");
    promoteurSelectBtn.firstElementChild.value = selectedLi.innerText;
}

promoteurSearchInp.addEventListener("keyup", () => {
    let arr = [];
    let searchWord = promoteurSearchInp.value.toLowerCase();
    arr = promoteurs.filter(data => {
        return data.toLowerCase().startsWith(searchWord);
    }).map(data => {
        let isSelected = data == promoteurSelectBtn.firstElementChild.value ? "selected" : "";
        return `<li onclick="updatePromoteurName(this)" class="flex items-center ${isSelected}">${data}</li>`;
    }).join("");
    promoteurOptions.innerHTML = arr ? arr : `<p style="margin-top: 10px;">Oops! Promoteur introuvable</p>`;
});

promoteurSelectBtn.addEventListener("click", () => promoteurWrapper.classList.toggle("active"));
</script>